version: '3.8'

services:
  api:
    container_name: api-uber
    image: uber-api:1.0
    build: ../../Users/felip/Downloads
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
 
